import { lieAppUrl as publicLieAppUrl } from '../content/site.mjs';

export function renderPage(page, locale, locales) {
const { company, research, product, contact, pages, ui, form } = locale;
const lieAppUrl = locale.id === 'zh' ? publicLieAppUrl : '';
const assetPrefix = locale.directory ? '../' : './';
const localeLink = (target, entry) => target.id === locale.id ? './' + entry.file : assetPrefix + (target.directory ? target.directory + '/' : '') + entry.file;
const alternates = locales.map(target => '<link rel="alternate" hreflang="' + target.lang + '" href="' + localeLink(target, page) + '">').join('') + '<link rel="alternate" hreflang="x-default" href="' + localeLink(locales[0], page) + '">';
const escape = (value) => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const arrow = '<span aria-hidden="true">↗</span>';
const button = (label, href, style = 'primary') => `<a class="button button--${style}" href="${escape(href)}">${label}${arrow}</a>`;
const eyebrow = (text) => `<p class="eyebrow"><span aria-hidden="true"></span>${text}</p>`;
const brand = `<span class="brand__name">${company.name}</span><span class="brand__english">${company.english}</span>`;
const invitation = (dark = false) => `<section class="invitation${dark ? ' invitation--dark' : ''}" aria-labelledby="invitation-title"><div class="container invitation__inner"><div>${eyebrow(ui.contactEyebrow)}<h2 id="invitation-title">${ui.invitation}</h2><p>${contact.description}</p></div><div class="button-row">${button(ui.researchContact, './contact.html?intent=research', dark ? 'light' : 'primary')}${button(ui.productContact, './contact.html?intent=product', dark ? 'dark-outline' : 'secondary')}</div></div></section>`;
const loopArt = `<div class="loop-art" aria-hidden="true"><svg viewBox="0 0 600 550" fill="none"><defs><radialGradient id="halo"><stop stop-color="#d4e0cc" stop-opacity=".7"/><stop offset="1" stop-color="#f7f5ee" stop-opacity="0"/></radialGradient><linearGradient id="stroke" x1="50" y1="0" x2="540" y2="500" gradientUnits="userSpaceOnUse"><stop stop-color="#9eb5a3"/><stop offset=".48" stop-color="#26745c"/><stop offset="1" stop-color="#b7a579"/></linearGradient></defs><circle cx="300" cy="275" r="266" fill="url(#halo)"/><g stroke="#d3d9cb" stroke-width=".8"><path d="M50 140H550M50 275H550M50 410H550M165 25V525M300 25V525M435 25V525"/><circle cx="300" cy="275" r="222" stroke-dasharray="2 9"/><circle cx="300" cy="275" r="150" stroke-dasharray="2 8"/></g><g stroke="url(#stroke)" stroke-width="1.5"><ellipse cx="300" cy="275" rx="223" ry="106" transform="rotate(-38 300 275)"/><ellipse cx="300" cy="275" rx="223" ry="106" transform="rotate(38 300 275)"/><ellipse cx="300" cy="275" rx="223" ry="106" transform="rotate(90 300 275)"/></g><g fill="#26745c"><circle cx="300" cy="52" r="5"/><circle cx="128" cy="372" r="5"/><circle cx="473" cy="374" r="5"/></g><circle cx="440" cy="175" r="7" fill="#b49b68"/><circle cx="300" cy="275" r="42" fill="#f7f5ee" stroke="#9fb4a0"/><circle cx="300" cy="275" r="30" stroke="#d2dace"/><path d="M286 275H314M300 261V289" stroke="#26745c" stroke-width="1.5"/><g fill="#a6b8a5"><circle cx="50" cy="140" r="2"/><circle cx="550" cy="410" r="2"/><circle cx="165" cy="25" r="2"/><circle cx="435" cy="525" r="2"/></g></svg><div class="art-caption"><span>${ui.artCaption}</span><span>KIZHARYN TECHNOLOGIES</span></div></div>`;
const researchDiagram = `<figure class="architecture-figure"><div class="figure-heading"><span>Stalyra</span><span>${ui.conceptDiagram}</span></div><div class="architecture" role="img" aria-label="${escape(ui.architectureAria)}"><div class="belief"><span>${ui.parentNode}</span><strong>${ui.jointBelief}</strong></div><div class="processes">${ui.processes.map(text => `<span>${text}</span>`).join('')}</div><div class="feedback"><div>${ui.actionResults}<span>${ui.and}</span>${ui.observations}</div><span class="feedback__arrow" aria-hidden="true">→</span><div>${ui.jointPosterior}<small>${ui.update}</small></div></div><div class="return-path"><span>${ui.writeBack}</span><i aria-hidden="true">↑</i></div></div><figcaption>${ui.architectureCaption}</figcaption></figure>`;
const researchOverview = `<figure class="architecture-figure research-overview"><div class="figure-heading"><span>Stalyra</span><span>${ui.architectureName}</span></div><div class="overview-map" aria-hidden="true"><div class="overview-core">Stalyra</div><div class="overview-labels">${ui.overviewLabels.map(text => `<span>${text}</span>`).join('')}</div></div><figcaption>${ui.overviewCaption}</figcaption></figure>`;
const productDiagram = `<figure class="product-figure"><div class="figure-heading"><span>LIE</span><span>${ui.integrationDiagram}</span></div><div class="product-flow"><div><small>${ui.input}</small><strong>${ui.learningData}</strong></div><span aria-hidden="true">↓</span><div class="engine"><small>${ui.learningEngine}</small><strong>LIE</strong></div><span aria-hidden="true">↓</span><div><small>${ui.output}</small><strong>${ui.structuredResults}</strong></div></div><figcaption>${ui.integrationCaption}</figcaption></figure>`;

const home = `<section class="hero" aria-labelledby="hero-title"><div class="container hero__grid"><div class="hero__copy">${eyebrow('KIZHARYN TECHNOLOGIES')}<h1 id="hero-title">${ui.heroTitle[0]}<span>${ui.heroTitle[1]}</span></h1><p class="hero__lead">${company.description}</p><div class="button-row">${button(ui.exploreResearch, './research.html')}${button(ui.viewProducts, './product.html', 'secondary')}</div><p class="hero__signature">${ui.signature}</p></div>${loopArt}</div><div class="container hero__bottom"><span>${ui.scope}</span><a href="#research">${ui.learnMore} <span aria-hidden="true">↓</span></a></div></section>
<section class="section-pad research-section" id="research" aria-labelledby="research-title"><div class="container split"><div><p class="section-index">01 <span>${ui.researchLabel}</span></p><h2 id="research-title">Stalyra<br><span class="serif">${ui.architectureName}</span></h2><p class="section-copy">${research.description}</p>${button(ui.learnStalyra, './research.html', 'secondary')}</div>${researchOverview}</div></section>
<section class="section-pad product-section" id="product" aria-labelledby="product-title"><div class="container split"><div><p class="section-index">02 <span>${ui.productLabel}</span></p><h2 id="product-title">LIE<span class="product-title-divider"> / </span><span class="serif">${ui.learningEngine}</span></h2><p class="section-copy">${product.description}</p><p class="section-copy section-copy--small">${ui.productTeaser}</p>${button(ui.learnLie, './product.html', 'light')}</div><div class="product-art" aria-hidden="true"><span class="product-art__top">LEARNING INTELLIGENCE ENGINE</span><div class="product-art__lines"><i></i><i></i><i></i><strong>LIE<span>${ui.learningEngine}</span></strong><i></i><i></i><i></i></div><span class="product-art__bottom">${ui.dataApplications}</span></div></div></section>${invitation()}`;

const researchPage = `<section class="page-hero"><div class="container">${eyebrow(ui.researchEyebrow)}<h1>Stalyra<span class="serif">${ui.architectureName}</span></h1><p class="english-subtitle">${research.english}</p><p class="page-lead">${research.description}</p></div></section><section class="section-pad section-tint"><div class="container"><div class="research-detail"><div><p class="section-index">01 <span>${ui.designLabel}</span></p><h2>${ui.designTitle}</h2><p class="research-overview-copy">${research.overview}</p></div>${researchOverview}</div><details class="architecture-details"><summary>${ui.architectureDetails}</summary><div class="research-detail"><div><h3>${research.name}</h3><p class="definition">${research.definition}</p><p class="architecture-note">${ui.architectureNote}</p></div>${researchDiagram}</div></details></div></section>${invitation(true)}`;

const productPage = `<section class="page-hero"><div class="container product-intro"><div>${eyebrow(ui.productEyebrow)}<h1>LIE<span class="serif">${ui.learningEngine}</span></h1><p class="english-subtitle">${product.english}</p><p class="page-lead">${product.description}</p><p class="section-copy section-copy--small">${product.introduction}</p><div class="button-row">${lieAppUrl ? button('体验 LIE', lieAppUrl) : ''}${button(ui.integrationContact, './contact.html?intent=product', lieAppUrl ? 'secondary' : 'primary')}</div></div>${productDiagram}</div></section><section class="section-pad section-tint"><div class="container"><div class="section-heading"><p class="section-index">01 <span>${ui.applicationsLabel}</span></p><h2>${ui.applicationsTitle}</h2><p>${ui.applicationsDescription}</p></div><div class="discussion-grid">${ui.discussions.map((item, index) => `<article><span class="item-number">0${index + 1}</span><h3>${item.title}</h3><p>${item.description}</p></article>`).join('')}</div></div></section>${invitation(true)}`;

const aboutPage = `<section class="page-hero about-hero"><div class="container">${eyebrow(ui.aboutEyebrow)}<h1>${ui.aboutTitle[0]}${locale.id === 'zh' ? '' : ' '}<span class="serif">${ui.aboutTitle[1]}</span></h1><div class="about-statement"><span>${company.name}<small>${company.english}</small></span><p>${company.description}</p></div></div></section><section class="section-pad section-tint"><div class="container about-grid"><div><p class="section-index">01 <span>${ui.directionLabel}</span></p><h2>${ui.mission}</h2><p class="section-copy">${ui.directionDescription.join('<br>')}</p></div><div class="direction-list"><a href="./research.html"><span>${ui.researchLabel}</span><div><h3>${research.name}</h3><p>${research.description}</p></div>${arrow}</a><a href="./product.html"><span>${ui.productLabel}</span><div><h3>${product.name}</h3><p>${product.description}</p></div>${arrow}</a></div></div></section>${invitation()}`;

const contactPage = `<section class="page-hero contact-hero"><div class="container">${eyebrow(ui.contactEyebrow)}<h1>${ui.contactTitle[0]}${locale.id === 'zh' ? '' : ' '}<span class="serif">${ui.contactTitle[1]}</span></h1><p class="page-lead">${contact.description}</p></div></section><section class="contact-section"><div class="container contact-layout"><aside class="contact-aside"><p class="section-index">${ui.contactMethods}</p><h2>${ui.cooperation}</h2><p>${ui.emailDescription}</p><a class="email-link" href="mailto:${company.email}">${company.email}${arrow}</a><a class="email-link email-link--secondary" href="mailto:${company.alternateEmail}">${company.alternateEmail}${arrow}</a><div class="contact-aside__note"><span aria-hidden="true">↗</span><p>${ui.researchContact}<br>${ui.productContact}</p></div></aside><div class="contact-card"><script id="contact-copy" type="application/json">${JSON.stringify(form).replaceAll('<', '\\u003c')}</script><form id="contact-form"><div class="form-heading"><h2>${form.title}</h2><p>${form.description}</p></div><div class="form-grid"><div class="form-field form-field--full"><label for="email">${form.email} <span>${form.required}</span></label><input id="email" name="email" type="email" autocomplete="email" maxlength="254" placeholder="you@example.com" required></div><fieldset class="intent-group form-field--full"><legend>${form.intent} <span>${form.requiredChoice}</span></legend><div><label><input type="radio" name="intent" value="research" required><span>${form.research}</span></label><label><input type="radio" name="intent" value="product" required><span>${form.product}</span></label></div></fieldset><div class="form-field"><label for="name">${form.name} <span>${form.optional}</span></label><input id="name" name="name" autocomplete="name" maxlength="80"></div><div class="form-field"><label for="organization">${form.organization} <span>${form.optional}</span></label><input id="organization" name="organization" autocomplete="organization" maxlength="160"></div><div class="form-field form-field--full"><label for="message">${form.message} <span>${form.required}</span></label><textarea id="message" name="message" rows="5" required maxlength="1800" placeholder="${escape(form.placeholder)}"></textarea></div></div><p class="form-notice">${form.notice}</p><button class="button button--primary form-submit" type="submit" disabled>${form.submit} ${arrow}</button><p class="form-status" id="contact-status" role="status" aria-live="polite"></p><div id="mail-actions" class="mail-actions" hidden><a id="mail-link" class="button button--primary" href="mailto:${company.email}">${form.openMail} ${arrow}</a><button id="copy-mail" class="button button--secondary" type="button">${form.copyMail}</button><p>${form.mailHelp}</p></div><noscript><p>${form.noScript}</p></noscript></form><details class="privacy-note" id="privacy"><summary>${form.privacyTitle}</summary><p>${form.privacyDescription}</p></details></div></div></section>`;

const bodies = { home, research: researchPage, product: productPage, about: aboutPage, contact: contactPage };
return `<!doctype html>\n<html lang="${locale.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><meta name="theme-color" content="#f7f5ee"><meta name="description" content="${escape(page.description)}">${alternates}<title>${escape(page.title)} · ${company.name} ${company.english}</title><link rel="icon" href="${assetPrefix}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${assetPrefix}assets/wireframe.css"><script src="${assetPrefix}assets/wireframe.js" defer></script></head><body data-page="${page.key}"><a class="skip-link" href="#main-content">${ui.skip}</a><header class="site-header"><div class="container site-header__inner"><a class="brand" href="./index.html" aria-label="${company.name} ${ui.homeLabel}">${brand}</a><nav class="main-nav" aria-label="${ui.mainNav}">${pages.map(item => `<a href="./${item.file}"${item.key === page.key ? ' aria-current="page"' : ''}>${item.label}</a>`).join('')}</nav><nav class="language-nav" aria-label="${ui.languageNav}">${locales.map(target => `<a href="${localeLink(target, page)}" lang="${target.lang}" hreflang="${target.lang}" data-language="${target.id}"${target.id === locale.id ? ' aria-current="true"' : ''}>${target.label}</a>`).join('')}</nav></div></header><main id="main-content" tabindex="-1">${bodies[page.key]}</main><footer class="site-footer"><div class="container footer-top"><a class="brand" href="./index.html">${brand}</a><p>${ui.footerScope.join('<br>')}</p><nav aria-label="${ui.footerNav}"><a href="./research.html">${ui.exploreResearch} ${arrow}</a><a href="./product.html">${ui.viewProducts} ${arrow}</a><a href="./contact.html">${ui.contactLink} ${arrow}</a></nav></div><div class="container footer-bottom"><span>© ${company.name} · ${company.english}</span><a href="${page.key === 'contact' ? '#privacy' : './contact.html#privacy'}">${form.privacyTitle}</a><span>${ui.mission}</span></div></footer></body></html>\n`;
}
